### ISSUE TITLE
Blas issue in JS

### ISSUE THREAD

**Issue by assaad** [datathings/greycat#13]
Blas has been desactivated in JS without any fallback on the constructor of this class on Feb 15, 2017: 
https://github.com/datathings/greycat/blob/master/plugins/ml/src/main/java/greycat/ml/common/matrix/blassolver/BlasMatrixEngine.java

**Comment by dukeboard** [comment]
Blas plugin is on the way

**Comment by dukeboard** [comment]
Blas plugin moved to enterprise version, doc coming accordingly
