### ISSUE TITLE
Generated .d.ts is malformed

### ISSUE THREAD

**Issue by maxleiko** [datathings/greycat#2]
This is how the `.d.ts` files should look like:

For  **greycat.d.ts**:
```ts
import * as java from 'greycat-java';

declare namespace greycat {
  // ... blabla
}

export = greycat
```
and it's **package.json** should refer to something like `greycat-java` as dependencies:

```json
{
  "name": "greycat",
  "version": "1.0.0",
  "dependencies": {
    "greycat-java": "1.0.0"
  }
}
```
(the package.json is minimalistic for the sake of readability here, but of course it should specify more than that)

and the **greycat-java.d.ts** should look like:

```ts
declare namespace java {
  // ...blabla...
}

export = java
```

And there you go.

Then in your "client" project that has nothing to do with **greycat** core, we just do:

```sh
npm i greycat -S
```

and in the code:

```js
import { GraphBuilder, Type } from 'greycat';

// do something with greycat as a client
```

**Comment by dukeboard** [comment]
Fixed in V2, to be release next coming days. Many thanks for reporting max!

**Comment by maxleiko** [comment]
👍

**Comment by dukeboard** [comment]
V2 pushed
