### ISSUE TITLE
Remove TYPE_NAME from Language

### ISSUE THREAD

**Issue by lmouline** [datathings/greycat#41]
The TYPE_NAME token could be (IMHO) removed from the language definition.
I don't see its usage. It could be easily replaced by the IDENT token :)

**Comment by thomashartmann** [comment]
Thx... I will remove it and in addition use labeling + sub rules:
Everything can be accessed by label or sub rule, this avoids implicit IDENT parsing.

**Comment by thomashartmann** [comment]
implemented in master for V8 release
