### ISSUE TITLE
Improve ModelChecker messages

### ISSUE THREAD

**Issue by lmouline** [datathings/greycat#42]
In error message from the ModelChecker, you could add line and/or column information.
From a context element, you can call `getStart` method then `getLine` and `getCharPositionInLine`

Example in [ModelChecker](https://github.com/datathings/greycat/blob/master/modeling/language/src/main/java/greycat/language/ModelChecker.java), line 55.

Before:
``` java
if (!isClassifierDeclared(parentClassFqn, modelDclCtx)) { 
    throw new RuntimeException(parentClassFqn + " is specified as parent of " + classFqn + " but is not declared");
}
```

Suggestion:
```java
if (!isClassifierDeclared(parentClassFqn, modelDclCtx)) { 
    throw new RuntimeException("line " + classDclCxt.parentDcl().getStart().getLine() + ":" + classDclCxt.parentDcl().getStart().getCharPositionInLine() + ":" + parentClassFqn + " is specified as parent of " + classFqn + " but is not declared");
}
```

**Comment by thomashartmann** [comment]
implemented in master for V8 release
