### ISSUE TITLE
Adding the support for Node removal

### ISSUE THREAD

**Issue by rouvoy** [datathings/greycat#5]
We would like GreyCat to support the removal of a Node from a Graph, so far we haven't seen such a support in the doc/code. Would that be possible to include?

**Comment by dukeboard** [comment]
Hello,
Yes you're right we should show this ability through this public API.
Do you need the delete of the full timeline of the node or just one timepoint ?
I will add it by the end of next week :-)

**Comment by rouvoy** [comment]
We only need to remove the node from a given timepoint to reflect the point in time it died :)

Thanks!

**Comment by dukeboard** [comment]
Ok so simple :-)

**Comment by dukeboard** [comment]
I'm sorry to see that this feature has been delayed so long :( we was very busy to with remote task API development. I will take care of this ASAP this week.

**Comment by dukeboard** [comment]
Feature coming and planned for version 8 :-) new method end() on node allows to terminate the lifespan of a node. Stay tuned!

**Comment by dukeboard** [comment]
So drop method and end has been added in v9 so feature closed :-)
