### ISSUE TITLE
Adding find methods on indexes

### ISSUE THREAD

**Issue by gnain** [datathings/greycat#51]
It would be convenient to have find methods on (a) relations when an index is specified; and (b) statically on classes, also when a global index in defined.
Hereunder two possible examples of methods to be generated

In the modeling example, it would be great to generate something like this, in Devices: 

== For Device.modules relation
```java
public final void findModules(greycat.Callback<Module[]> callback, String name, String name2) {
this.getRelationIndexed(MODULES).find(result -> callback.on((Module[])result), this.world(), this.time(), Module.NAME, name, Module.NAME2, name2);
}
```

== For Devices global
```java
public static final void find(greycat.Callback<Device[]> callback, Graph graph, long world, long time, String name) {
graph.index(world, time, Device.MYKEY,result -> {
result.find(result1 -> callback.on((Device[])result1), Device.NAME, name);
});
}
```

**Comment by thomashartmann** [comment]
(a) relations when an index is specified: 
we cannot cast in Java Node[] to MyType[]. I copy the Node[] to MyType[] instead in the generated method.

**Comment by thomashartmann** [comment]
implemented on master for v9
