### ISSUE TITLE
DeclareAttribute not generated for local indexes

### ISSUE THREAD

**Issue by gnain** [datathings/greycat#55]
From a generated class, is you try to look for a value in the index (to check if it already exists), before any update, you get the following exception
```javascript
greycat.js:4665 Uncaught TypeError: Cannot read property 'size' of null
    at CoreIndexAttribute.find (greycat.js:4665)
    at Workspace.findPreset (pwmodel.js:1836)
```
I think
1. decalreAttribute() should be call for each local index
2. find should be protected in case the index has no attribute

**Comment by dukeboard** [comment]
fixed in trunk, will be released in V10
