### ISSUE TITLE
Action Println is not working

### ISSUE THREAD

**Issue by bogdan-xplode** [datathings/greycat#6]
.then(println("{{result}}")) is not printing anything.

**Comment by dukeboard** [comment]
Print create an output at the end of the task accessible through the final result.output(). If you want to print directly I suggest to use the log task instead. Does it solve your problem?

**Comment by bogdan-xplode** [comment]
Great, many thanks!

**Comment by dukeboard** [comment]
No problem . Fell free to reopen if any further trouble. ;)
