### ISSUE TITLE
[Feature Request][GCM]Return directly the object in the callback of method find for indexes

### ISSUE THREAD

**Issue by electricalwind** [datathings/greycat#68]
## Context

Alongside the declaration of an index (either global or local) in GCM, the method find is generated with the following signature: 

```java
public static final void find(Graph graph, long world, long time, String name,
      Callback<MyIndexableObjectl[]> callback) {}
```
Once call the method will thus return in the callback the node if it exists, in an array of size one, and an empty array otherwise. As partial requests when indexing is done on more than one field is not supported then the size of the array in the callback is doomed to be either 0 or 1. Thus wouldn't it make more sense to return the object in the callback and null if the node doesn't exist?

## Expected result

The generated code would thus look like this:

```java
public static final void find(Graph graph, long world, long time, String name,
      Callback<MyIndexableObjectl> callback) {}
```

## Point of discussion 

I agree that this is in fact, the general behaviour of greycat, and that it actually prevents null pointer exception, but for the generated code it could make more sense to directly return the object. ;)

**Comment by gnain** [comment]
Thanks for the report and suggestion ! :-)

Actually, the unicity is not guaranteed by the index, because it is not a primary key; just an index allowing to access faster to an element.
Therefore, you can always have several nodes, indexed by the same key. The use of an array in the callback is thus mandatory.

Thanks again for you help and suggestions to improve GreyCat 👍

**Comment by electricalwind** [comment]
Thanks for the reply, 
I always assumed that the unicity was guaranted but it's true that in fact I was enforcing it myself ;)
I will add it to the documentation ;)
