### ISSUE TITLE
Enums in greycat model?

### ISSUE THREAD

**Issue by DataWorm** [datathings/greycat#71]
Hello,

is there a way to create enums in greycat or do I have to work around it like creating a class with constants mapped to some value and assign those values apart from a real enum and checking that the assigned value really matches to one of these constants?!

Greetings
DataWorm

**Comment by dukeboard** [comment]
Hi,
At the moment (v10.3) you have to use constants mapped to values as you said. We were used to having the enum in the .gcm file before but finally, people were afraid that they are some magic inside so we finally expose constants in a transparent way. The second reason to make values appears explicitly is to ensure the consistency of already created storage while adding new enum value. Nonetheless, if you have specific needs which could motivate the re-introduction of the enum, technically this can be done very fast.

**Comment by lmouline** [comment]
I don't know if it is a good practise but I saw Enum as attribute constraints, i.e., to specify the set of value that an attribute could have. 
I had the case where I had an attribute for representing a status. Something that I wanted to have:

```
class Action {
   att status: ActionStatus
}

enum ActionStatus {
   PENDING, RUNNING, FINISHED
}
```

An idea is that GCM could define an enum as a set of constants for removing the "magic effect" (if I understood well what you mentioned with it).



Two suggestions:
```
enum ActionStatus {
   const att PENDING: String = "PENDING"
   const att RUNNING: String = "RUNNING"
   const att FINISHED: String = "FINISHED"
}
```

Or

```
enum ActionStatus: String {
   PENDING = "PENDING",
   RUNNING= "RUNNING",
   FINISHED = "FINISHED"
}
```

But I don't know if:
  - you could propagate this "constraint" to the Node/Chunk level
  - this is a good practice and the proper solution wouldn't be to have a constraint language

**Comment by thomashartmann** [comment]
For now (v10), we decided to use constants instead of "real" enum objects for performance reasons. 
However, in v11 we will introduce a way to seamlessly add custom types into GreyCat. This mechanism can also be used for defining enums.
