### ISSUE TITLE
How to retrieve all existing nodes?

### ISSUE THREAD

**Issue by abourdon** [datathings/greycat#83]
Hello,

Maybe I missed something but I can't see any explanation or example to retrieve all existing nodes from a given graph.

Is this operation conceptually correct? If yes, what could I use in the API to do it?

Thanks,
Aurélien

**Comment by assaad** [comment]
Hello, we don't index all the nodes in the graph, it will be too much nodes. 

Therefore you need to create and declare an index, and then index the nodes you like. You can have several indexes, and after you have a method find to query the index.

Here is a sample code:
https://github.com/datathings/greycat-samples/blob/master/src/main/java/greycat/samples/Index.java
Note that the index is temporal, meaning it will resolve different set of nodes at different times. 
If you want to index everything together, use time 0 always on the index. 
Sorry again for the lack of documentation.

**Comment by abourdon** [comment]
Thank you @assaad
