### ISSUE TITLE
Base64.Java line 404 protect against null string

### ISSUE THREAD

**Issue by assaad** [datathings/greycat#92]
If i have a string array and some elements are null, i get an exception at the file Base64.Java line 404. 
Should we protect against null there or not?

**Comment by gnain** [comment]
On load, empty Strings in StringArrays are loaded as null; then on serialize, empty string were null.
I protected the Base64 encoder for Strings to just return when String is null. Same behavior as with empty Strings.
Closed by a41cd1e5ede79e1495a57b02299fc66ba6511603
